package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type Schema struct {
	Version int       `json:"version"`
	Methods []Method  `json:"methods"`
	Types   []TypeDef `json:"types"`
}

type Method struct {
	Name  string `json:"name"`
	Group string `json:"group"`
}

type TypeDef struct {
	Name   string  `json:"name"`
	Fields []Field `json:"fields"`
}

type Field struct {
	JSONName string `json:"json"`
	GoType   string `json:"go"`
	O        int    `json:"o"`
}

var methodAbbreviations = map[string]string{
	"api":  "API",
	"id":   "ID",
	"url":  "URL",
	"mcp":  "MCP",
	"lsp":  "LSP",
	"json": "JSON",
	"usd":  "USD",
}

var fieldAbbreviations = map[string]string{
	"api": "API",
	"id":  "ID",
	"url": "URL",
	"usd": "USD",
	"kb":  "KB",
}

func snakeToPascal(s string, abbrevs map[string]string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		lower := strings.ToLower(part)
		if abbr, ok := abbrevs[lower]; ok {
			parts[i] = abbr
		} else {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func methodNameToConst(name string) string {
	parts := strings.Split(name, "/")
	for i, part := range parts {
		parts[i] = snakeToPascal(part, methodAbbreviations)
	}
	return "Method" + strings.Join(parts, "")
}

func fieldNameToGo(name string) string {
	return snakeToPascal(name, fieldAbbreviations)
}

func parseGoType(goType string, forceOmitempty bool) (string, bool) {
	if strings.HasPrefix(goType, "[") && strings.HasSuffix(goType, "]") {
		inner := goType[1 : len(goType)-1]
		return "[]" + inner, forceOmitempty
	}
	if strings.HasPrefix(goType, "*") {
		inner := goType[1:]
		switch inner {
		case "bool", "int64", "float64", "string", "uint64", "int", "float32", "int32":
			return inner, true
		default:
			return "*" + inner, forceOmitempty
		}
	}
	return goType, forceOmitempty
}

func main() {
	schemaPath := flag.String("schema", "", "path to schema.json")
	outDir := flag.String("out", "", "output directory for generated files")
	flag.Parse()

	if err := run(*schemaPath, *outDir); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// run 执行生成全链；错误文案带阶段前缀（与历史 stderr 输出一致）。
// 从 main 中提出以便单测直调（子进程路径对 coverage 不可见）。
func run(schemaPath, outDir string) error {
	if schemaPath == "" {
		schemaPath = filepath.Join("..", "eos-core-rs", "crates", "eos-core-protocol", "schema.json")
	}

	data, err := os.ReadFile(schemaPath)
	if err != nil {
		return fmt.Errorf("read schema: %v", err)
	}

	var schema Schema
	if err := json.Unmarshal(data, &schema); err != nil {
		return fmt.Errorf("parse schema: %v", err)
	}

	if outDir == "" {
		outDir = filepath.Join("pkg", "coreapi", "generated")
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %v", err)
	}

	if err := generateMethods(schema, outDir); err != nil {
		return fmt.Errorf("generate methods: %v", err)
	}

	if err := generateTypes(schema, outDir); err != nil {
		return fmt.Errorf("generate types: %v", err)
	}

	if err := generateTest(schema, outDir); err != nil {
		return fmt.Errorf("generate test: %v", err)
	}

	fmt.Printf("Generated %d methods, %d types in %s\n", len(schema.Methods), len(schema.Types), outDir)
	return nil
}

func generateMethods(schema Schema, outDir string) error {
	var b strings.Builder
	b.WriteString("// Code generated by protocol-gen; DO NOT EDIT.\n\n")
	b.WriteString("package generated\n\n")

	b.WriteString("const (\n")
	for _, m := range schema.Methods {
		fmt.Fprintf(&b, "\t%s = %q\n", methodNameToConst(m.Name), m.Name)
	}
	b.WriteString(")\n\n")

	b.WriteString("func CoreMethods() []string {\n")
	b.WriteString("\treturn []string{\n")
	for _, m := range schema.Methods {
		fmt.Fprintf(&b, "\t\t%s,\n", methodNameToConst(m.Name))
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	groups := make(map[string][]string)
	for _, m := range schema.Methods {
		groups[m.Group] = append(groups[m.Group], methodNameToConst(m.Name))
	}

	groupNames := make([]string, 0, len(groups))
	for g := range groups {
		groupNames = append(groupNames, g)
	}
	sort.Strings(groupNames)

	b.WriteString("func MethodGroups() map[string][]string {\n")
	b.WriteString("\treturn map[string][]string{\n")
	for _, g := range groupNames {
		fmt.Fprintf(&b, "\t\t%q: {\n", g)
		for _, c := range groups[g] {
			fmt.Fprintf(&b, "\t\t\t%s,\n", c)
		}
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	return os.WriteFile(filepath.Join(outDir, "methods_gen.go"), []byte(b.String()), 0o644)
}

func generateTypes(schema Schema, outDir string) error {
	needsJSON := false
	for _, t := range schema.Types {
		for _, f := range t.Fields {
			if f.GoType == "json.RawMessage" {
				needsJSON = true
				break
			}
		}
		if needsJSON {
			break
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by protocol-gen; DO NOT EDIT.\n\n")
	b.WriteString("package generated\n\n")

	if needsJSON {
		b.WriteString("import \"encoding/json\"\n\n")
	}

	for _, t := range schema.Types {
		fmt.Fprintf(&b, "type %s struct {\n", t.Name)
		for _, f := range t.Fields {
			goType, omitempty := parseGoType(f.GoType, f.O > 0)
			goName := fieldNameToGo(f.JSONName)

			jsonTag := f.JSONName
			if omitempty {
				jsonTag += ",omitempty"
			}

			fmt.Fprintf(&b, "\t%s %s `json:\"%s\"`\n", goName, goType, jsonTag)
		}
		b.WriteString("}\n\n")
	}

	return os.WriteFile(filepath.Join(outDir, "types_gen.go"), []byte(b.String()), 0o644)
}

func generateTest(schema Schema, outDir string) error {
	var b strings.Builder
	b.WriteString("package generated\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"sort\"\n")
	b.WriteString("\t\"testing\"\n\n")
	b.WriteString("\t\"github.com/eosaios/eos/pkg/protocol/jsonrpc\"\n")
	b.WriteString(")\n\n")

	b.WriteString("func TestGeneratedMethodsCoverAllCoreMethods(t *testing.T) {\n")
	b.WriteString("\texpected := jsonrpc.AllCoreMethods()\n")
	b.WriteString("\tgot := CoreMethods()\n\n")
	b.WriteString("\tsort.Strings(expected)\n")
	b.WriteString("\tsort.Strings(got)\n\n")
	b.WriteString("\texpectedSet := make(map[string]bool, len(expected))\n")
	b.WriteString("\tfor _, m := range expected {\n")
	b.WriteString("\t\texpectedSet[m] = true\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tgotSet := make(map[string]bool, len(got))\n")
	b.WriteString("\tfor _, m := range got {\n")
	b.WriteString("\t\tgotSet[m] = true\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tfor _, m := range expected {\n")
	b.WriteString("\t\tif !gotSet[m] {\n")
	b.WriteString("\t\t\tt.Errorf(\"CoreMethods() missing method %q from AllCoreMethods()\", m)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tfor _, m := range got {\n")
	b.WriteString("\t\tif !expectedSet[m] {\n")
	b.WriteString("\t\t\tt.Errorf(\"CoreMethods() has extra method %q not in AllCoreMethods()\", m)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	return os.WriteFile(filepath.Join(outDir, "schema_test.go"), []byte(b.String()), 0o644)
}
